### ISSUE TITLE
Separate system_modes from MROS

### ISSUE THREAD

**Issue by Rezenders** [meta-control/mc_mros_reasoner#139]
Right now system_modes' services are being called from the reasoner, making it mandatory to use system_modes. It should be possible to use it with something else.

**Comment by jeroenzwan** [comment]
I attempted to solve this and have opened a pull request. I made the system modes bridge in the pipeline_exemplar repository (I will open a pull request there as well), but I don't know if this is the best place. I opened #150, since there was also the issue of not having a node defined for which the system_mode needs to be changed.
